// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBItwB7aeJDMFlHHOWTG7GrWiBVJawLJ2A',
    appId: '1:250689335369:web:1638d07354b57160968f98',
    messagingSenderId: '250689335369',
    projectId: 'movie-app-f2dc7',
    authDomain: 'movie-app-f2dc7.firebaseapp.com',
    storageBucket: 'movie-app-f2dc7.firebasestorage.app',
    measurementId: 'G-TBGPN1XL2R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdNn4HlVxkkYrs7Uf8l0NbobSFiRppBuQ',
    appId: '1:250689335369:android:edeeee6b521407bf968f98',
    messagingSenderId: '250689335369',
    projectId: 'movie-app-f2dc7',
    storageBucket: 'movie-app-f2dc7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8Ox4NXVQcy2VB38EW7RieYciJFELSGJs',
    appId: '1:250689335369:ios:4544869b758596ca968f98',
    messagingSenderId: '250689335369',
    projectId: 'movie-app-f2dc7',
    storageBucket: 'movie-app-f2dc7.firebasestorage.app',
    iosBundleId: 'com.example.testMovies',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8Ox4NXVQcy2VB38EW7RieYciJFELSGJs',
    appId: '1:250689335369:ios:e3d8b867bc50b775968f98',
    messagingSenderId: '250689335369',
    projectId: 'movie-app-f2dc7',
    storageBucket: 'movie-app-f2dc7.firebasestorage.app',
    iosBundleId: 'com.example.movie',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBItwB7aeJDMFlHHOWTG7GrWiBVJawLJ2A',
    appId: '1:250689335369:web:320cdb7334c8a17c968f98',
    messagingSenderId: '250689335369',
    projectId: 'movie-app-f2dc7',
    authDomain: 'movie-app-f2dc7.firebaseapp.com',
    storageBucket: 'movie-app-f2dc7.firebasestorage.app',
    measurementId: 'G-61E2VG4L2X',
  );
}
